set -g mouse on
set -g status on
set -g status-interval 5
set -g escape-time 10
set-hook -g session-closed 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g client-detached 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g window-linked 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g window-unlinked 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g pane-exited 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g after-new-window 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g after-split-window 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g after-kill-window 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g after-kill-pane 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g after-rename-window 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
set-hook -g after-new-session 'run-shell "/usr/local/bin/code-server-omp-tmux-save-state"'
